import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import { ClearLocalstorage } from "./ClearLocalstorage";

const josefilSans = Josefin_Sans({ variable: "--font-josefin-sans", subsets: ["latin"] });

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });

const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = { title: "Create Next App", description: "Generated by create next app" };

export default function root_layout({ children }: LayoutProps<"/">) {
	return (
		<html
			lang="en"
			className={`${geistSans.variable} ${geistMono.variable} ${josefilSans.variable} h-full antialiased`}>
			<body className="min-h-full flex flex-col font-geist bg-yellow-50">
				<ClearLocalstorage />
				{children}
			</body>
		</html>
	);
}
